runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:Cc31fTfL7cKDAeWHhD8Md84IuMpSU7RxVFYZG0NE73o=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
